/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugaspraktikum2;

/**
 *
 * @author Moklet
 */
public class tp2 extends javax.swing.JFrame {
    public tp2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cb = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        Ds = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Namap = new javax.swing.JTextField();
        Jabatan = new javax.swing.JTextField();
        Jk = new javax.swing.JTextField();
        Umur = new javax.swing.JTextField();
        NIS = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(null);

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "Ketua Kelas", "Wakil Ketua Kelas", "Sekretaris", "Bendahara 1", "Bendahara 2" }));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        jPanel2.add(cb);
        cb.setBounds(140, 60, 150, 30);

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel3.setLayout(null);

        Ds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DsActionPerformed(evt);
            }
        });
        jPanel3.add(Ds);
        Ds.setBounds(180, 460, 170, 30);

        jLabel12.setText("Dokter Spesialis");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(50, 460, 130, 30);

        Namap.setEnabled(false);
        Namap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamapActionPerformed(evt);
            }
        });
        jPanel3.add(Namap);
        Namap.setBounds(150, 70, 200, 30);

        Jabatan.setEnabled(false);
        Jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JabatanActionPerformed(evt);
            }
        });
        jPanel3.add(Jabatan);
        Jabatan.setBounds(150, 270, 200, 30);

        Jk.setEnabled(false);
        Jk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JkActionPerformed(evt);
            }
        });
        jPanel3.add(Jk);
        Jk.setBounds(150, 190, 200, 30);

        Umur.setEnabled(false);
        Umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmurActionPerformed(evt);
            }
        });
        jPanel3.add(Umur);
        Umur.setBounds(150, 150, 200, 30);

        NIS.setEnabled(false);
        NIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NISActionPerformed(evt);
            }
        });
        jPanel3.add(NIS);
        NIS.setBounds(150, 110, 200, 30);

        Nama.setEnabled(false);
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        jPanel3.add(Nama);
        Nama.setBounds(150, 30, 200, 30);

        jLabel13.setText("Nama");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 30, 130, 30);

        jLabel5.setText("NIS");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 110, 130, 30);

        jLabel6.setText("Umur");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 150, 120, 30);

        jLabel7.setText("Jenis Kelamin");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 190, 130, 30);

        jLabel9.setText("Jabatan");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 270, 130, 30);

        jLabel11.setText("Nama Panggilan");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 70, 130, 30);

        jLabel8.setText("Alamat");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 230, 130, 30);

        Alamat.setEnabled(false);
        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        jPanel3.add(Alamat);
        Alamat.setBounds(150, 230, 200, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(50, 120, 370, 320);

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel3.setText("STRUKTUR ORGANISASI KELAS XI RPL 1");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 20, 410, 30);

        jLabel2.setText("Pilih Pengurus");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 60, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-10, -10, 460, 490);

        setBounds(0, 0, 467, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        if(cb.getSelectedItem().equals("Ketua Kelas")){
            Nama.setText("Nasih Ahmad Fatikhuddin");
            Namap.setText("Nasih");
            NIS.setText("4784/1503.070");
            Umur.setText("17 Tahun");
            Jk.setText("Laki-Laki");
            Alamat.setText("JL. Danau Maninjau III G2F/11");
            Jabatan.setText("Ketua Kelas");
        }
        else
        if(cb.getSelectedItem().equals("Wakil Ketua Kelas")){
            Nama.setText("Rafidia Aqil Ramadhan");
            Namap.setText("Rafid");
            NIS.setText("4897/1526.070");
            Umur.setText("17 Tahun");
            Jk.setText("Laki-Laki");
            Alamat.setText("JL. Danau Maninjau III G2F/11");
            Jabatan.setText("Wakil Ketua Kelas");
        }
        else
        if(cb.getSelectedItem().equals("Sekretaris")){
            Nama.setText("Dhenarra Erine Aisyahsari");
            Namap.setText("Erin");
            NIS.setText("4697/1416.070");
            Umur.setText("17 Tahun");
            Jk.setText("Perempuan");
            Alamat.setText("JL. Kerinci V G6 C12");
            Jabatan.setText("Sekretaris");
        }
        else
        if(cb.getSelectedItem().equals("Bendahara 1")){
            Nama.setText("Armaningtyas Utami");
            Namap.setText("Arma");
            NIS.setText("4672/1591.070");
            Umur.setText("17 Tahun");
            Jk.setText("Perempuan");
            Alamat.setText("JL. Danau Towuti IV G5E 11");
            Jabatan.setText("Bendahara 1");
        }
        else
        if(cb.getSelectedItem().equals("Bendahara 2")){
            Nama.setText("Faiqoh");
            Namap.setText("Faiqoh");
            NIS.setText("4709/1427.070");
            Umur.setText("17 Tahun");
            Jk.setText("Perempuan");
            Alamat.setText("JL. Danau Ranau II G2D 11");
            Jabatan.setText("Bendahara 2");
        }
    }//GEN-LAST:event_cbActionPerformed

    private void DsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DsActionPerformed

    private void NamapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamapActionPerformed

    private void JabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JabatanActionPerformed

    private void JkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JkActionPerformed

    private void UmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UmurActionPerformed

    private void NISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NISActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tp2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Ds;
    private javax.swing.JTextField Jabatan;
    private javax.swing.JTextField Jk;
    private javax.swing.JTextField NIS;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Namap;
    private javax.swing.JTextField Umur;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
